services:
  nginx:
    container_name: nginx
    image: nginx:1.19.4
    restart: unless-stopped
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - strapiNetwork
    depends_on:
      - frontend
  
  namecheap-ddns:
    image: joshuamorris3/namecheap-ddns-update
    build:
      context: ./namecheap-ddns
      dockerfile: Dockerfile
    container_name: namecheap_ddns_updater
    restart: unless-stopped
    env_file: .env
    networks:
      - strapiNetwork

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./frontend/package.json:/opt/package.json
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /opt/app/src
          ignore:
            -node_modules/
        - action: rebuild
          path: package.json`
    networks:
      - strapiNetwork

volumes:
  pgdata:

networks:
  strapiNetwork:
    driver: bridge