services:
  nginx:
    container_name: nginx
    image: nginx:1.19.4
    restart: unless-stopped
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - strapiNetwork
    depends_on:
      - frontend

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./frontend/package.json:/opt/package.json
    ports:
      - "3000:3000"
    networks:
      - strapiNetwork

volumes:
  pgdata:

networks:
  strapiNetwork:
    driver: bridge